### ISSUE TITLE
Cannot use in typescript + vite environnement

### ISSUE THREAD

**Issue by xlaussel** [FriendsOfSymfony/FOSJsRoutingBundle#441]
I try to use the router in a typescript + vite environnement.
I import the library like:

`import {Routing} from '~/vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js/router'`

(~ is an alias to the root folder)

But when executing I have the following error in the console:
`Uncaught SyntaxError: The requested module '/@fs/data/xlextent/srcs/financile/vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js/router.js' does not provide an export named 'Routing' (at routing.ts:3:1)
`

When I do:

`import Routing from '~/vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js/router'`

I have the error:

But when executing I have the following error in the console:
`Uncaught SyntaxError: The requested module '/@fs/data/xlextent/srcs/financile/vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js/router.js' does not provide an export named 'default' (at routing.ts:3:1)
`

Here is my tsconfig.json with esModuleInterop ans allowJs set:

```
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "compilerOptions": {
    "esModuleInterop": true,
    "allowJs": true,
    "paths": {
      "@/*": ["./src/*"],
      "~/*": ["../*"],
    }
  },

  "references": [
    {
      "path": "./tsconfig.config.json"
    }
  ]
}
```

What can I do?

**Comment by fatso83** [comment]
So strange. It [most definitely has a `Router` export](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/js/router.ts#L49), but I have not checked the transpiled code.

**Comment by r4pt0s** [comment]
I know this is a quite old issue but I came across the same problem.
If you use vite instead of webpack (or it doesn't matter I guess) you can simple import the router.ts file directly instead of using the transpiled js files.
If you yarn add or npm installed `./vendor/friendsofsymfony/jsrouting-bundle/Resources/` then you should be able to import the router.ts file with

```javascript
import Routing from 'fos-router/js/router';
```
